### ISSUE TITLE
Синхронизироваться с апстримом

### ISSUE THREAD

**Issue by slowlime** [GREEN-ITMO-YADRO/flow#22]
В апстриме нас никто не ждёт, поэтому работа там продолжается полным ходом. В частности, в последних коммитах были какие-то изменения, связанные со строковыми константами, которые могли решить одну из выявленных нами проблем.

Для облегчения жизни стоит пулльнуть коммиты с апстрима в наш форк.

**Comment by astrophysik** [comment]
Попытался сделать через инструменты github sync fork, но он не сработал. Сделал пр с вливанием изменений https://github.com/YAGRIT/circt/pull/4
